import React from "react";
import HeaderForDash from "./HeaderForDash";

export default function dashboard() {
	return (
		<div>
			<HeaderForDash />
			<div>
				jdnjvnczndamx.z,xhfudhfxjdhfufhdjkhuligdsjsjcnxmcbxjkfhsfwkhrfosiehfidfyldifyjdsfbesgryugrbejhbhjbsdjgqwejwgjwgdhjsdh
				jdnjvnczndamx.z,xhfudhfxjdhfufhdjkhuligdsjsjcnxmcbxjkfhsfwkhrfosiehfidfyldifyjdsfbesgryugrbejhbhjbsdjgqwejwgjwgdhjsdh
				jdnjvnczndamx.z,xhfudhfxjdhfufhdjkhuligdsjsjcnxmcbxjkfhsfwkhrfosiehfidfyldifyjdsfbesgryugrbejhbhjbsdjgqwejwgjwgdhjsdh
				jdnjvnczndamx.z,xhfudhfxjdhfufhdjkhuligdsjsjcnxmcbxjkfhsfwkhrfosiehfidfyldifyjdsfbesgryugrbejhbhjbsdjgqwejwgjwgdhjsdh
				jdnjvnczndamx.z,xhfudhfxjdhfufhdjkhuligdsjsjcnxmcbxjkfhsfwkhrfosiehfidfyldifyjdsfbesgryugrbejhbhjbsdjgqwejwgjwgdhjsdh
				jdnjvnczndamx.z,xhfudhfxjdhfufhdjkhuligdsjsjcnxmcbxjkfhsfwkhrfosiehfidfyldifyjdsfbesgryugrbejhbhjbsdjgqwejwgjwgdhjsdh
				jdnjvnczndamx.z,xhfudhfxjdhfufhdjkhuligdsjsjcnxmcbxjkfhsfwkhrfosiehfidfyldifyjdsfbesgryugrbejhbhjbsdjgqwejwgjwgdhjsdh
				jdnjvnczndamx.z,xhfudhfxjdhfufhdjkhuligdsjsjcnxmcbxjkfhsfwkhrfosiehfidfyldifyjdsfbesgryugrbejhbhjbsdjgqwejwgjwgdhjsdh
				jdnjvnczndamx.z,xhfudhfxjdhfufhdjkhuligdsjsjcnxmcbxjkfhsfwkhrfosiehfidfyldifyjdsfbesgryugrbejhbhjbsdjgqwejwgjwgdhjsdh
				jdnjvnczndamx.z,xhfudhfxjdhfufhdjkhuligdsjsjcnxmcbxjkfhsfwkhrfosiehfidfyldifyjdsfbesgryugrbejhbhjbsdjgqwejwgjwgdhjsdh
				jdnjvnczndamx.z,xhfudhfxjdhfufhdjkhuligdsjsjcnxmcbxjkfhsfwkhrfosiehfidfyldifyjdsfbesgryugrbejhbhjbsdjgqwejwgjwgdhjsdh
				jdnjvnczndamx.z,xhfudhfxjdhfufhdjkhuligdsjsjcnxmcbxjkfhsfwkhrfosiehfidfyldifyjdsfbesgryugrbejhbhjbsdjgqwejwgjwgdhjsdh
				jdnjvnczndamx.z,xhfudhfxjdhfufhdjkhuligdsjsjcnxmcbxjkfhsfwkhrfosiehfidfyldifyjdsfbesgryugrbejhbhjbsdjgqwejwgjwgdhjsdh
				jdnjvnczndamx.z,xhfudhfxjdhfufhdjkhuligdsjsjcnxmcbxjkfhsfwkhrfosiehfidfyldifyjdsfbesgryugrbejhbhjbsdjgqwejwgjwgdhjsdh
				jdnjvnczndamx.z,xhfudhfxjdhfufhdjkhuligdsjsjcnxmcbxjkfhsfwkhrfosiehfidfyldifyjdsfbesgryugrbejhbhjbsdjgqwejwgjwgdhjsdh
				jdnjvnczndamx.z,xhfudhfxjdhfufhdjkhuligdsjsjcnxmcbxjkfhsfwkhrfosiehfidfyldifyjdsfbesgryugrbejhbhjbsdjgqwejwgjwgdhjsdh
				jdnjvnczndamx.z,xhfudhfxjdhfufhdjkhuligdsjsjcnxmcbxjkfhsfwkhrfosiehfidfyldifyjdsfbesgryugrbejhbhjbsdjgqwejwgjwgdhjsdh
			</div>
		</div>
	);
}
